export interface IntegrationDoc {
  id: string;
  title: string;
  subtitle: string;
  description: string;
  whatItDoes: string;
  howToConnect: string[];
  customConnector?: string;
  permissions: string[];
  supportedActions: string[];
  exampleUseCases: string[];
  usingSafely: string[];
  troubleshooting: { question: string; answer: string }[];
  faq?: { question: string; answer: string }[];
}

export const integrationDocs: Record<string, IntegrationDoc> = {
  gmail: {
    id: "gmail",
    title: "Gmail integration",
    subtitle: "Connect your Gmail account so Metawurks can access your emails and help you with reading, searching, and sending mail—all inside the chat.",
    description: "Connect your Gmail account so Metawurks can access your emails and help you with reading, searching, and sending mail—all inside the chat.",
    whatItDoes: "The Gmail connector lets Metawurks work with your Gmail inside the app. Once connected, you can ask the AI to read emails, search your inbox, summarize threads, draft replies, and send emails on your behalf. Your credentials are never stored in plain text; we use OAuth and store tokens securely per account.",
    howToConnect: [
      "Open Knowledge Sources (upload icon in the sidebar) and go to the Integrations tab.",
      "Click the Gmail card.",
      "On the Gmail detail page, click Connect.",
      "You'll be redirected to Google's sign-in and consent screen. Sign in with the Google account you want to use.",
      "Review the permissions and approve access. Metawurks will then complete the connection and show Gmail as connected.",
    ],
    customConnector: "Want to connect a different email provider? You can add custom MCP connectors from the Custom tab in Integrations. Enter your MCP server URL and Metawurks will connect to any compatible service.",
    permissions: [
      "Read your emails and labels",
      "Search your inbox",
      "Send emails on your behalf",
      "Compose and modify drafts",
      "Access basic profile info (e.g. email address) to identify the account",
    ],
    supportedActions: [
      "Search emails by keyword, sender, date, or label",
      "Read and summarize email threads",
      "Draft new emails or replies",
      "Send emails directly from the chat",
      "List recent emails or unread messages",
      "Find attachments in emails",
    ],
    exampleUseCases: [
      '"Summarize my unread emails from today"',
      '"Find the last email from John about the project"',
      '"Draft a reply thanking them for the meeting"',
      '"Send the drafted email"',
      '"Search for invoices from last month"',
    ],
    usingSafely: [
      "Review emails before sending—AI drafts may need adjustments",
      "Don't share sensitive credentials in the chat",
      "You can disconnect Gmail anytime from the Integrations tab",
      "Revoking access in Google Account settings will also disconnect",
    ],
    troubleshooting: [
      { question: "Connection failed?", answer: "Try signing out of Google and reconnecting." },
      { question: "Permissions error?", answer: "Make sure you approved all requested scopes." },
      { question: "Emails not showing?", answer: "Check if the connected account is correct." },
      { question: "Need help?", answer: "Contact support at admin@metawurks.com" },
    ],
    faq: [
      { question: "Is my Google password stored by Metawurks?", answer: "No. We use OAuth authentication, which means you sign in directly with Google. Your password is never shared with or stored by Metawurks." },
      { question: "How do I disconnect Gmail?", answer: "Go to Knowledge Sources → Integrations tab → Gmail → Click Disconnect. You can also revoke access from your Google Account settings." },
      { question: "Can Metawurks read all my emails?", answer: "Metawurks can only access emails when you ask it to. It doesn't continuously read or monitor your inbox in the background." },
      { question: "Will emails sent through Metawurks show in my Sent folder?", answer: "Yes. Any email sent through Metawurks will appear in your Gmail Sent folder, just like emails you send directly from Gmail." },
      { question: "Can I connect multiple Gmail accounts?", answer: "Currently, you can connect one Gmail account per Metawurks account. To switch accounts, disconnect the current one and connect a different Gmail account." },
    ],
  },

  "google-calendar": {
    id: "google-calendar",
    title: "Google Calendar integration",
    subtitle: "Connect your Google Calendar so Metawurks can view and manage events, check availability, and help you schedule—all inside the chat.",
    description: "Connect your Google Calendar so Metawurks can view and manage events, check availability, and help you schedule—all inside the chat.",
    whatItDoes: "The Google Calendar connector lets Metawurks work with your calendar inside the app. Once connected, you can ask the AI to view upcoming events, create new meetings, check your availability, and manage your schedule. Your credentials are never stored in plain text; we use OAuth and store tokens securely per account.",
    howToConnect: [
      "Open Knowledge Sources (upload icon in the sidebar) and go to the Integrations tab.",
      "Click the Google Calendar card.",
      "On the Google Calendar detail page, click Connect.",
      "You'll be redirected to Google's sign-in and consent screen. Sign in with the Google account you want to use.",
      "Review the permissions and approve access. Metawurks will then complete the connection and show Google Calendar as connected.",
    ],
    customConnector: "Need to connect a different calendar service? You can add custom MCP connectors from the Custom tab in Integrations. Enter your MCP server URL to connect any compatible calendar service.",
    permissions: [
      "View your calendars",
      "View events on your calendars",
      "Create, edit, and delete events",
      "Access basic profile info (e.g. email address) to identify the account",
    ],
    supportedActions: [
      "List upcoming events for today, this week, or custom date range",
      "Create new calendar events with title, time, and attendees",
      "Update existing events",
      "Delete events",
      "Check availability for scheduling",
      "View event details including attendees and location",
    ],
    exampleUseCases: [
      '"What meetings do I have today?"',
      '"Schedule a meeting with John tomorrow at 2pm"',
      '"Am I free on Friday afternoon?"',
      '"Cancel my 3pm meeting"',
      '"Show me my schedule for next week"',
    ],
    usingSafely: [
      "Review event details before creating—AI may need adjustments",
      "Double-check attendee emails before sending invites",
      "You can disconnect Google Calendar anytime from the Integrations tab",
      "Revoking access in Google Account settings will also disconnect",
    ],
    troubleshooting: [
      { question: "Connection failed?", answer: "Try signing out of Google and reconnecting." },
      { question: "Permissions error?", answer: "Make sure you approved all requested scopes." },
      { question: "Events not showing?", answer: "Check if the connected account is correct." },
      { question: "Need help?", answer: "Contact support at admin@metawurks.com" },
    ],
    faq: [
      { question: "Can Metawurks create events on my calendar without asking?", answer: "No. Metawurks will only create, edit, or delete events when you explicitly ask it to. It won't make changes to your calendar automatically." },
      { question: "Will attendees receive invites for events created through Metawurks?", answer: "Yes. If you add attendees to an event, Google Calendar will send them an invitation email just like it would for events you create directly." },
      { question: "Can I connect multiple Google Calendars?", answer: "When you connect your Google account, Metawurks can access all calendars associated with that account, including shared calendars you have access to." },
      { question: "Does Metawurks store my calendar data?", answer: "No. Metawurks reads your calendar data in real-time when you make a request. It doesn't store a copy of your calendar events." },
      { question: "Can I limit which calendars Metawurks can access?", answer: "Currently, Metawurks has access to all calendars in your connected Google account. You can disconnect anytime if you want to revoke access." },
    ],
  },

  outlook: {
    id: "outlook",
    title: "Outlook integration",
    subtitle: "Connect your Outlook account so Metawurks can access your emails and calendar, helping you with reading, searching, and sending mail—all inside the chat.",
    description: "Connect your Outlook account so Metawurks can access your emails and calendar, helping you with reading, searching, and sending mail—all inside the chat.",
    whatItDoes: "The Outlook connector lets Metawurks work with your Microsoft Outlook email and calendar inside the app. Once connected, you can ask the AI to read emails, search your inbox, draft replies, send emails, and access your calendar. Your credentials are never stored in plain text; we use OAuth and store tokens securely per account.",
    howToConnect: [
      "Open Knowledge Sources (upload icon in the sidebar) and go to the Integrations tab.",
      "Click the Outlook card.",
      "On the Outlook detail page, click Connect.",
      "You'll be redirected to Microsoft's sign-in and consent screen. Sign in with the Microsoft account you want to use.",
      "Review the permissions and approve access. Metawurks will then complete the connection and show Outlook as connected.",
    ],
    customConnector: "Want to connect a different email or calendar service? You can add custom MCP connectors from the Custom tab in Integrations. Enter your MCP server URL to connect any compatible service.",
    permissions: [
      "Read your emails",
      "Send emails on your behalf",
      "Access your calendar",
      "Read your contacts",
      "Access basic profile info to identify the account",
    ],
    supportedActions: [
      "Search emails by keyword, sender, date, or folder",
      "Read and summarize email threads",
      "Draft new emails or replies",
      "Send emails directly from the chat",
      "List recent emails or unread messages",
      "Access calendar events",
    ],
    exampleUseCases: [
      '"Summarize my unread Outlook emails"',
      '"Find the last email from Sarah about the budget"',
      '"Draft a reply to the meeting invite"',
      '"Send the drafted email"',
      '"What\'s on my Outlook calendar today?"',
    ],
    usingSafely: [
      "Review emails before sending—AI drafts may need adjustments",
      "Don't share sensitive credentials in the chat",
      "You can disconnect Outlook anytime from the Integrations tab",
      "Revoking access in Microsoft Account settings will also disconnect",
    ],
    troubleshooting: [
      { question: "Connection failed?", answer: "Try signing out of Microsoft and reconnecting." },
      { question: "Permissions error?", answer: "Make sure you approved all requested scopes." },
      { question: "Emails not showing?", answer: "Check if the connected account is correct." },
      { question: "Need help?", answer: "Contact support at admin@metawurks.com" },
    ],
    faq: [
      { question: "Can I use both personal and work Outlook accounts?", answer: "You can connect either a personal Microsoft account or a work/school account. Currently, one account can be connected at a time." },
      { question: "Does this work with Outlook desktop app?", answer: "This integration connects to your Outlook mailbox in the cloud, so it works with both Outlook web and desktop as they share the same mailbox." },
      { question: "Can Metawurks access my Outlook contacts?", answer: "Yes, with your permission. This helps when you want to send emails to contacts by name instead of typing their full email address." },
      { question: "Will emails sent through Metawurks appear in my Sent Items?", answer: "Yes. Any email sent through Metawurks will appear in your Outlook Sent Items folder, just like emails you send directly." },
      { question: "Is my Microsoft password stored by Metawurks?", answer: "No. We use OAuth authentication, which means you sign in directly with Microsoft. Your password is never shared with or stored by Metawurks." },
    ],
  },

  teams: {
    id: "teams",
    title: "Microsoft Teams integration",
    subtitle: "Connect Microsoft Teams so Metawurks can send messages, access channels, and help you collaborate with your team—all inside the chat.",
    description: "Connect Microsoft Teams so Metawurks can send messages, access channels, and help you collaborate with your team—all inside the chat.",
    whatItDoes: "The Microsoft Teams connector lets Metawurks work with your Teams workspace inside the app. Once connected, you can ask the AI to send messages, list channels, access conversations, and collaborate with your team. Your credentials are never stored in plain text; we use OAuth and store tokens securely per account.",
    howToConnect: [
      "Open Knowledge Sources (upload icon in the sidebar) and go to the Integrations tab.",
      "Click the Microsoft Teams card.",
      "On the Teams detail page, click Connect.",
      "You'll be redirected to Microsoft's sign-in and consent screen. Sign in with your Microsoft account.",
      "Review the permissions and approve access. Metawurks will then complete the connection and show Teams as connected.",
    ],
    customConnector: "Need to connect a different collaboration tool? You can add custom MCP connectors from the Custom tab in Integrations. Enter your MCP server URL to connect any compatible messaging service.",
    permissions: [
      "Read and send messages in channels",
      "Read and send chat messages",
      "View team and channel information",
      "View team members",
      "Access basic profile info to identify the account",
    ],
    supportedActions: [
      "Send messages to channels and chats",
      "List available teams and channels",
      "View recent messages in a channel",
      "Search through conversations",
      "View team member information",
      "Access chat history",
    ],
    exampleUseCases: [
      '"Send a message to the Marketing channel"',
      '"What are the recent messages in the General channel?"',
      '"List all my Teams channels"',
      '"Who is in the Engineering team?"',
      '"Search for messages about the product launch"',
    ],
    usingSafely: [
      "Review messages before sending—AI drafts may need adjustments",
      "Be careful when sending to public channels",
      "You can disconnect Teams anytime from the Integrations tab",
      "Revoking access in Microsoft Account settings will also disconnect",
    ],
    troubleshooting: [
      { question: "Connection failed?", answer: "Try signing out of Microsoft and reconnecting." },
      { question: "Permissions error?", answer: "Make sure you approved all requested scopes." },
      { question: "Channels not showing?", answer: "Check if you have access to the teams." },
      { question: "Need help?", answer: "Contact support at admin@metawurks.com" },
    ],
    faq: [
      { question: "Can Metawurks access private channels?", answer: "Metawurks can only access channels you are a member of. Private channels are accessible only if you have been added to them." },
      { question: "Will my team members know when I send a message through Metawurks?", answer: "Messages sent through Metawurks appear as coming from you. Team members won't know if you sent it directly or through Metawurks." },
      { question: "Can I access multiple Teams workspaces?", answer: "The integration connects to the Teams workspace associated with your Microsoft account. To access a different workspace, reconnect with an account that has access to it." },
      { question: "Does Metawurks store my Teams messages?", answer: "No. Metawurks reads messages in real-time when you ask for them. It doesn't store a copy of your Teams conversations." },
      { question: "Can Metawurks join or schedule Teams meetings?", answer: "Currently, the Teams integration focuses on messaging. For scheduling meetings, use the Outlook or Google Calendar integration." },
    ],
  },

  slack: {
    id: "slack",
    title: "Slack integration",
    subtitle: "Connect Slack so Metawurks can send messages, access channels, and help you collaborate with your team—all inside the chat.",
    description: "Connect Slack so Metawurks can send messages, access channels, and help you collaborate with your team—all inside the chat.",
    whatItDoes: "The Slack connector lets Metawurks work with your Slack workspace inside the app. Once connected, you can ask the AI to send messages, list channels, search conversations, and collaborate with your team. Your credentials are never stored in plain text; we use OAuth and store tokens securely per account.",
    howToConnect: [
      "Open Knowledge Sources (upload icon in the sidebar) and go to the Integrations tab.",
      "Click the Slack card.",
      "On the Slack detail page, click Connect.",
      "You'll be redirected to Slack's sign-in and consent screen. Sign in with your Slack workspace.",
      "Review the permissions and approve access. Metawurks will then complete the connection and show Slack as connected.",
    ],
    customConnector: "Want to connect a different messaging platform? You can add custom MCP connectors from the Custom tab in Integrations. Enter your MCP server URL to connect any compatible workspace.",
    permissions: [
      "Read messages in channels you're a member of",
      "Send messages to channels",
      "View channel information",
      "View user profiles",
      "Access workspace information",
    ],
    supportedActions: [
      "Send messages to channels and direct messages",
      "List available channels",
      "View recent messages in a channel",
      "Search through conversations",
      "View user profiles",
      "Access message history",
    ],
    exampleUseCases: [
      '"Send a message to the #general channel"',
      '"What are the recent messages in #engineering?"',
      '"List all my Slack channels"',
      '"Search for messages about the launch"',
      '"Who posted in #announcements today?"',
    ],
    usingSafely: [
      "Review messages before sending—AI drafts may need adjustments",
      "Be careful when sending to public channels",
      "You can disconnect Slack anytime from the Integrations tab",
      "Revoking access in Slack settings will also disconnect",
    ],
    troubleshooting: [
      { question: "Connection failed?", answer: "Try signing out of Slack and reconnecting." },
      { question: "Permissions error?", answer: "Make sure you approved all requested scopes." },
      { question: "Channels not showing?", answer: "Check if you're a member of those channels." },
      { question: "Need help?", answer: "Contact support at admin@metawurks.com" },
    ],
    faq: [
      { question: "Can Metawurks access private Slack channels?", answer: "Metawurks can only access channels you are a member of, including private channels you've been added to." },
      { question: "Will my teammates know messages were sent through Metawurks?", answer: "No. Messages sent through Metawurks appear as coming from you. There's no indication that they were sent via Metawurks." },
      { question: "Can I connect multiple Slack workspaces?", answer: "Currently, you can connect one Slack workspace per Metawurks account. To switch workspaces, disconnect the current one and connect a different workspace." },
      { question: "Does Metawurks store my Slack messages?", answer: "No. Metawurks reads messages in real-time when you make a request. It doesn't store a copy of your Slack conversations." },
      { question: "Can Metawurks send direct messages to my coworkers?", answer: "Yes, Metawurks can send direct messages on your behalf when you explicitly ask it to. Always review before sending." },
    ],
  },

  figma: {
    id: "figma",
    title: "Figma integration",
    subtitle: "Connect Figma so Metawurks can access your design files, projects, and help you collaborate on designs—all inside the chat.",
    description: "Connect Figma so Metawurks can access your design files, projects, and help you collaborate on designs—all inside the chat.",
    whatItDoes: "The Figma connector lets Metawurks work with your Figma files inside the app. Once connected, you can ask the AI to browse design files, view project details, access team files, and get file version history. Your credentials are never stored in plain text; we use OAuth and store tokens securely per account.",
    howToConnect: [
      "Open Knowledge Sources (upload icon in the sidebar) and go to the Integrations tab.",
      "Click the Figma card.",
      "On the Figma detail page, click Connect.",
      "You'll be redirected to Figma's sign-in and consent screen. Sign in with your Figma account.",
      "Review the permissions and approve access. Metawurks will then complete the connection and show Figma as connected.",
    ],
    customConnector: "Need to connect a different design tool? You can add custom MCP connectors from the Custom tab in Integrations. Enter your MCP server URL to connect any compatible design service.",
    permissions: [
      "Read your files and projects",
      "Access team information",
      "View file comments",
      "Access file version history",
      "Read basic profile info to identify the account",
    ],
    supportedActions: [
      "List design files and projects",
      "View file details and metadata",
      "Browse team files and folders",
      "Get file version history",
      "View comments on designs",
      "Access component libraries",
    ],
    exampleUseCases: [
      '"List my recent Figma files"',
      '"Show me the details of the Homepage design"',
      '"What comments are on the Mobile App file?"',
      '"Get the version history of this file"',
      '"List all files in the Marketing team"',
    ],
    usingSafely: [
      "This connector provides read-only access to your designs",
      "Sensitive design files remain in your Figma account",
      "You can disconnect Figma anytime from the Integrations tab",
      "Revoking access in Figma settings will also disconnect",
    ],
    troubleshooting: [
      { question: "Connection failed?", answer: "Try signing out of Figma and reconnecting." },
      { question: "Permissions error?", answer: "Make sure you approved all requested scopes." },
      { question: "Files not showing?", answer: "Check if you have access to the team or project." },
      { question: "Need help?", answer: "Contact support at admin@metawurks.com" },
    ],
    faq: [
      { question: "Can Metawurks edit my Figma designs?", answer: "No. The Figma integration provides read-only access. Metawurks can view your files and information but cannot make changes to your designs." },
      { question: "Can I access team libraries through Metawurks?", answer: "Yes. If you have access to team libraries in Figma, Metawurks can help you browse and find components in those libraries." },
      { question: "Does Metawurks store copies of my design files?", answer: "No. Metawurks reads file information in real-time from Figma. Your design files remain only in your Figma account." },
      { question: "Can Metawurks access files shared with me?", answer: "Yes. Metawurks can access any files you have permission to view in Figma, including files shared with you by others." },
      { question: "Will my team see that I connected Metawurks?", answer: "No. Connecting Metawurks to your Figma account is private. Your team members won't be notified about the connection." },
    ],
  },

  linkedin: {
    id: "linkedin",
    title: "LinkedIn integration",
    subtitle: "Connect LinkedIn so Metawurks can access your professional profile and network—all inside the chat.",
    description: "Connect LinkedIn so Metawurks can access your professional profile and network—all inside the chat.",
    whatItDoes: "The LinkedIn connector lets Metawurks work with your LinkedIn profile inside the app. Once connected, you can ask the AI to view your profile information, access your connections, and manage your professional network. Your credentials are never stored in plain text; we use OAuth and store tokens securely per account.",
    howToConnect: [
      "Open Knowledge Sources (upload icon in the sidebar) and go to the Integrations tab.",
      "Click the LinkedIn card.",
      "On the LinkedIn detail page, click Connect.",
      "You'll be redirected to LinkedIn's sign-in and consent screen. Sign in with your LinkedIn account.",
      "Review the permissions and approve access. Metawurks will then complete the connection and show LinkedIn as connected.",
    ],
    customConnector: "Want to connect a different professional network? You can add custom MCP connectors from the Custom tab in Integrations. Enter your MCP server URL to connect any compatible service.",
    permissions: [
      "Read your profile information",
      "Access your connections",
      "View your network",
      "Read basic profile info to identify the account",
    ],
    supportedActions: [
      "View your profile information",
      "Access your connections list",
      "Search your network",
      "View company pages",
      "Get profile details",
    ],
    exampleUseCases: [
      '"Show me my LinkedIn profile"',
      '"List my recent connections"',
      '"Search for connections at Google"',
      '"What\'s my current job title on LinkedIn?"',
      '"How many connections do I have?"',
    ],
    usingSafely: [
      "This connector provides read-only access to your profile",
      "Your LinkedIn credentials are never stored",
      "You can disconnect LinkedIn anytime from the Integrations tab",
      "Revoking access in LinkedIn settings will also disconnect",
    ],
    troubleshooting: [
      { question: "Connection failed?", answer: "Try signing out of LinkedIn and reconnecting." },
      { question: "Permissions error?", answer: "Make sure you approved all requested scopes." },
      { question: "Profile not showing?", answer: "Check if the connected account is correct." },
      { question: "Need help?", answer: "Contact support at admin@metawurks.com" },
    ],
    faq: [
      { question: "Can Metawurks post on my LinkedIn profile?", answer: "No. The LinkedIn integration provides read-only access to your profile and connections. Metawurks cannot create posts or send messages on your behalf." },
      { question: "Can Metawurks see my LinkedIn messages?", answer: "No. The integration focuses on profile and connection data. Your LinkedIn messages remain private and are not accessible through this integration." },
      { question: "Is my LinkedIn password stored by Metawurks?", answer: "No. We use OAuth authentication, which means you sign in directly with LinkedIn. Your password is never shared with or stored by Metawurks." },
      { question: "Can Metawurks send connection requests?", answer: "No. Metawurks has read-only access and cannot send connection requests, messages, or perform any actions on your LinkedIn account." },
      { question: "Will my connections know I connected Metawurks?", answer: "No. Connecting Metawurks to LinkedIn is private. Your connections and profile visitors won't know about the integration." },
    ],
  },

  fireflies: {
    id: "fireflies",
    title: "Fireflies integration",
    subtitle: "Connect Fireflies so Metawurks can access your meeting transcripts, summaries, and AI-powered meeting notes—all inside the chat.",
    description: "Connect Fireflies so Metawurks can access your meeting transcripts, summaries, and AI-powered meeting notes—all inside the chat.",
    whatItDoes: "The Fireflies connector lets Metawurks work with your meeting transcripts inside the app. Once connected, you can ask the AI to access transcripts, search meeting notes, get summaries, and find action items from your meetings. Your API key is stored securely and used to authenticate with the Fireflies API.",
    howToConnect: [
      "Open Knowledge Sources (upload icon in the sidebar) and go to the Integrations tab.",
      "Click the Fireflies card.",
      "On the Fireflies detail page, click Connect. A popup will appear asking for your Fireflies API Key.",
      "To get your API key: Go to fireflies.ai → Sign in → Settings → Integrations → API & Webhooks → Copy your API key.",
      "Paste the API key into the popup and click Connect Account. Metawurks will complete the connection and show Fireflies as connected.",
    ],
    customConnector: "Need to connect a different meeting transcription tool? You can add custom MCP connectors from the Custom tab in Integrations. Enter your MCP server URL to connect any compatible service.",
    permissions: [
      "Access your meeting transcripts",
      "View meeting summaries",
      "Read action items",
      "Access meeting participants info",
      "Read basic profile info to identify the account",
    ],
    supportedActions: [
      "Access meeting transcripts",
      "Search through meeting notes",
      "Get AI-generated meeting summaries",
      "Find and track action items",
      "View meeting participants",
      "Access historical meeting data",
    ],
    exampleUseCases: [
      '"Show me the transcript from yesterday\'s meeting"',
      '"What were the action items from the product review?"',
      '"Summarize my meeting with the design team"',
      '"Search for discussions about the budget"',
      '"List my recent meetings"',
    ],
    usingSafely: [
      "This connector provides read-only access to your transcripts",
      "Meeting data remains in your Fireflies account",
      "You can disconnect Fireflies anytime from the Integrations tab",
      "You can regenerate your API key in Fireflies settings to revoke access",
    ],
    troubleshooting: [
      { question: "Connection failed?", answer: "Make sure your API key is correct. Go to Fireflies Settings → Integrations → API & Webhooks to verify or regenerate your key." },
      { question: "Invalid API key error?", answer: "Your API key may have expired or been regenerated. Get a new key from Fireflies and reconnect." },
      { question: "Transcripts not showing?", answer: "Ensure your Fireflies account has recorded meetings and the API key has the correct permissions." },
      { question: "Need help?", answer: "Contact support at admin@metawurks.com" },
    ],
    faq: [
      { question: "Is my Fireflies API key stored securely?", answer: "Yes. Your API key is encrypted and stored securely. It is only used to authenticate with Fireflies when you make a request." },
      { question: "Does Metawurks store my meeting transcripts?", answer: "No. Metawurks accesses transcripts in real-time from Fireflies when you request them. Your transcripts remain stored only in your Fireflies account." },
      { question: "Can Metawurks join my meetings and record them?", answer: "No. Metawurks only accesses transcripts that have already been recorded by Fireflies. It cannot join or record meetings itself." },
      { question: "How do I revoke Metawurks access to Fireflies?", answer: "You can disconnect from the Integrations tab in Metawurks, or regenerate your API key in Fireflies settings to invalidate the old key." },
      { question: "Will meeting participants know I'm using Metawurks?", answer: "No. Accessing transcripts through Metawurks is private. Other meeting participants won't be notified about the integration." },
    ],
  },
};

export const integrationsList = [
  { id: "gmail", name: "Gmail" },
  { id: "google-calendar", name: "Google Calendar" },
  { id: "outlook", name: "Outlook" },
  { id: "teams", name: "Microsoft Teams" },
  { id: "slack", name: "Slack" },
  { id: "figma", name: "Figma" },
  { id: "linkedin", name: "LinkedIn" },
  { id: "fireflies", name: "Fireflies" },
];
